### ISSUE TITLE
invalid service notification error while uploading image

### ISSUE THREAD

**Issue by vipul1905** [NativeScript/nativescript-background-http#85]
I am trying to single image. But I get the following error

````
An uncaught Exception occurred on "main" thread.
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 groupKey=net.gotev vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

````

This is the upload function:

````
 displayImage(){
        var documents = fs.knownFolders.temp();

        documents.getEntities()
        .then((entities)=>{
            // entities is array with the document's files and folders.
            entities.forEach((entity)=>{
                console.log(entity);
                console.log(entity.path);
                
                let token = appSettings.getString("token");
                console.log(token);
                if (token != ''){

                    var request = {
                        url:  url
                        method: "POST",
                        headers: {
                            "Content-Type": "application/octet-stream",
                            "File-Name": entity.path,
                            "Authorization": "Bearer " + token  
                        },
                        description: "{ 'uploading': 'bigpig.jpg' }"
                    };
                    
                    var task = session.uploadFile(entity.path, request);
                    
                    task.on("progress", this.logEvent);
                    task.on("error", this.logEvent);
                    task.on("complete", this.logEvent);
                    
                   
              }
            });
        }, function (error) {
            // Failed to obtain folder's contents.
            // globalConsole.error(error.message);
        });

````
the entity path is " /data/user/0/org.testApp.testApp/cache/savedImage1510757546373.jpg". I tried to save the image to the temp folder of the emulator and find the file and upload to the server.

Could anyone tell me what is missing? and what this error means? Any help would be much appreciated. Thanks.

**Comment by tsonevn** [comment]
Hi @vipul1905,
I tested your scenario on my side while using the attached code, however, I was unable to recreate the reported error. Could you provide sample project, which could be debugged locally. It would also help if you could provide more info about your environment(CLI modules, node, npm) and info about the device or simulator, which is used for testing.

**Comment by tsonevn** [comment]
closing due to inactivity

**Comment by NickIliev** [comment]
Reproduce via [this demo application](https://github.com/NickIliev/NS-Issues-2018/tree/master/nativescript-background-http/issue_99) on API levels 26 and 27

**Comment by LorenDorez** [comment]
I too am having this issue after upgrading to API 27. Any resolution yet?

**Comment by LorenDorez** [comment]
for now i just do this on the request object and things are working again

```
androidDisplayNotificationProgress: false
```

**Comment by mariuspruski** [comment]
This is still the case with version 3.2.1 when using `androidDisplayNotificationProgress: true`
When setting this property to false, we get a different exception, namely:
```
JS: ERROR Error: Uncaught (in promise): Error: java.lang.IllegalArgumentException: Android Oreo requires a notification configuration for the service to run. https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)
JS:     net.gotev.uploadservice.UploadRequest.startUpload(UploadRequest.java:72)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
```

As far as I can see, this library in its newest version ALWAYS needs a notificationConfig, otherwise it will throw this exception.

We will stay on version 3.2.0 with notifications disabled, as this seems to be the only working way on Android Oreo.

**Comment by b0uda** [comment]
@mariuspruski Please can you be more specific about how to resolve this issue

**Comment by LorenDorez** [comment]
@b0uda , I resolved this by upgrading to the latest version. This issue should be fixed. Make sure to remove the `androidDisplayNotificationProgress: false` or set it back to `true`

**Comment by b0uda** [comment]
@mariuspruski thx for your quick reply , updated all modules and still have the same error

**Comment by c13andka** [comment]
I have this problem on all Android 8.1 phones
